In [4]:
#逆行列の求め方
from pprint import pprint
import scipy.linalg as linalg   # SciPy Linear Algebra Library
import numpy as np

A = np.array([[1,1,-2],[1,-2,1],[1,-2,-1]])
b = np.array([[-4],[5],[2]])
#pprint(A)
#pprint(b)
inv_A = linalg.inv(A)
print(inv_A)
np.dot(inv_A,b)

[[ 0.66666667  0.83333333 -0.5       ]
 [ 0.33333333  0.16666667 -0.5       ]
 [ 0.          0.5        -0.5       ]]


array([[ 0.5],
       [-1.5],
       [ 1.5]])

In [21]:
#問題1
#LU分解、上・下三角行列、連立方程式の解
from pprint import pprint
import scipy.linalg as linalg   # SciPy Linear Algebra Library
import numpy as np

#！！！！数値を変える！！！！
A = np.array([[1.0,4,3],[1,-2,1],[2,-2,-1]])
A0 = np.array([[1.0,4,3],[1,-2,1],[2,-2,-1]])
b = np.array([[11.0],[11],[11]])

n = 3
L = np.identity(n)
T = []
for i in range(n):        #i行目
    T.append(np.identity(n))
    for j in range(i+1, n):
        am = A[j,i]/A[i,i]    #i行の要素を使って，i+1行目の先頭を消す係数を求める
        T[i][j,i]=-am         #i番目の消去行列に要素を入れる
        L[j,i]=am             #LTMの要素
        for k in range(n):
            A[j,k] -= am*A[i,k] #もとの行列をUTMにしていく
        b[j] -= b[i]*am   #数値ベクトルも操作
pprint(L)
pprint(A)
pprint(b)

array([[1.      , 0.      , 0.      ],
       [1.      , 1.      , 0.      ],
       [2.      , 1.666667, 1.      ]])
array([[ 1.      ,  4.      ,  3.      ],
       [ 0.      , -6.      , -2.      ],
       [ 0.      ,  0.      , -3.666667]])
array([[ 11.],
       [  0.],
       [-11.]])


In [24]:
#問題2
#pivot付のLU分解
from pprint import pprint
import scipy.linalg as linalg   # SciPy Linear Algebra Library
import numpy as np

A = np.array([[3.0, 2, 2, 1],[3, 2, 3, 1],[1,-2,-3,1], [5,3,-2,5]])
#A0 = np.array([[3.0, 2, 2, 1],[3, 2, 3, 1],[1,-2,-3,1], [5,3,-2,5]])
b = np.array([[-6.0],[2],[-9],[2]])
e_A = np.hstack((A, b))
pprint(e_A)
P, L, U = linalg.lu(e_A)  #LU分解

print("P:")
pprint(P)

print("L:")
pprint(L)

print("U:")
pprint(U)

print("P,A:")
e_B = np.dot(P,A)
pprint(e_B)

print("L,U:")
e_C = np.dot(L,U)
pprint(e_C)

array([[ 3.,  2.,  2.,  1., -6.],
       [ 3.,  2.,  3.,  1.,  2.],
       [ 1., -2., -3.,  1., -9.],
       [ 5.,  3., -2.,  5.,  2.]])
P:
array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])
L:
array([[ 1.      ,  0.      ,  0.      ,  0.      ],
       [ 0.2     ,  1.      ,  0.      ,  0.      ],
       [ 0.6     , -0.076923,  1.      ,  0.      ],
       [ 0.6     , -0.076923,  0.75    ,  1.      ]])
U:
array([[ 5.      ,  3.      , -2.      ,  5.      ,  2.      ],
       [ 0.      , -2.6     , -2.6     , -0.      , -9.4     ],
       [ 0.      ,  0.      ,  4.      , -2.      ,  0.076923],
       [ 0.      ,  0.      ,  0.      , -0.5     , -7.980769]])
P,A:
array([[ 5.,  3., -2.,  5.],
       [ 1., -2., -3.,  1.],
       [ 3.,  2.,  3.,  1.],
       [ 3.,  2.,  2.,  1.]])
L,U:
array([[ 5.,  3., -2.,  5.,  2.],
       [ 1., -2., -3.,  1., -9.],
       [ 3.,  2.,  3.,  1.,  2.],
       [ 3.,  2.,  2.,  1., -6.]])


In [29]:
#問題3
#Gauss-Seidel法
#（Jacobi法はプリントNo.5の9ページにあります）
import numpy as np
np.set_printoptions(precision=6, suppress=True)

#！！！配列ここで変える！！！
A=np.array([[5,1,1,1],[1,3,1,1],[1,-2,-9,1],[1,3,-2,5]])
b=np.array([-6,2,-7,3])
n=4
x0=np.zeros(n)

for iter in range(0, 20):    #行数
    for i in range(0, n):　　#列数
        x1=b[i]
        for j in range(0, n):
            x1=x1-A[i][j]*x0[j]
        x1=x1+A[i][i]*x0[i]
        x1=x1/A[i][i]
        x0[i]=x1
    print(x0)
    
#Jacobi法と収束性の説明
print("\nガウスザイデル法を用いた方が,ヤコビ法を用いた方よりも早く収束する.")
print("ヤコビ法は一連の計算が終わった後に解を更新するが、ガウスザイデル法は、1つのforループが終わるごとに解を更新する。")
print("そのため変数の個数は1つでよくなり,配列を必要としない.")
print("よって前のXの値を用いて次のXの値を求めるのでより早く解が定まる.")




[-1.2       1.066667  0.407407  0.362963]
[-1.567407  0.932346  0.436763  0.528779]
[-1.579578  0.871345  0.46739   0.580064]
[-1.58376   0.845435  0.478382  0.600844]
[-1.584932  0.835236  0.482827  0.608976]
[-1.585408  0.831202  0.484574  0.61219 ]
[-1.585593  0.82961   0.485264  0.613458]
[-1.585666  0.828981  0.485537  0.613959]
[-1.585695  0.828733  0.485644  0.614157]
[-1.585707  0.828635  0.485687  0.614235]
[-1.585711  0.828597  0.485703  0.614266]
[-1.585713  0.828581  0.48571   0.614278]
[-1.585714  0.828575  0.485713  0.614283]
[-1.585714  0.828573  0.485714  0.614284]
[-1.585714  0.828572  0.485714  0.614285]
[-1.585714  0.828572  0.485714  0.614286]
[-1.585714  0.828572  0.485714  0.614286]
[-1.585714  0.828571  0.485714  0.614286]
[-1.585714  0.828571  0.485714  0.614286]
[-1.585714  0.828571  0.485714  0.614286]

ガウスザイデル法を用いた方が,ヤコビ法を用いた方よりも早く収束する.
ヤコビ法は一連の計算が終わった後に解を更新するが、ガウスザイデル法は、1つのforループが終わるごとに解を更新する。
そのため変数の個数は1つでよくなり,配列を必要としない.
よって前のXの値を用いて次のXの値を求めるのでより早く解が定まる.
