In [6]:
#問題1
import numpy as np
#！！！配列変える！！！
A = np.array([[0,1,-2],[-3,7,-3],[3,-5,5]])
l, P = np.linalg.eig( A )
print("固有値 A：")
print(l)
print("固有ベクトル（対角化行列） P：")
print(P)

固有値 A：
[ 1.000  9.000  2.000]
固有ベクトル（対角化行列） P：
[[-0.905  0.229 -0.707]
 [-0.302  0.688  0.000]
 [ 0.302 -0.688  0.707]]


In [7]:
from pprint import pprint
print("対角化：")
dA = np.dot(np.linalg.inv(P),np.dot(A,P))
np.set_printoptions(precision=3, suppress=True)
pprint(dA)

対角化：
array([[ 1.,  0.,  0.],
       [-0.,  9., -0.],
       [ 0.,  0.,  2.]])


In [8]:
#問題2_1
#ページランクを求める
from pprint import pprint
from numpy import array, zeros, diagflat, dot, transpose
from scipy.linalg import eig

#！！！ここ変える！！！
#グラフを見て、→が出てたら1、そうでなければ0
A = array([[0,1,1,1,1,0,1], #1→1,6は0、1→2,3,4,5,7は1
           [1,0,0,0,0,0,0], #2→1は1、それ以外は0
           [1,1,0,0,0,0,0],
           [0,1,1,0,1,0,0],
           [1,0,1,1,0,1,0],
           [1,0,0,0,1,0,0],
           [0,0,0,0,1,0,0]])
diag = []
for i in range(0,7): #ページの数（必要あれば変える）
    tmp = 0.0
    for j in range(0,7):
        tmp += A[i,j]
    diag.append(1.0/tmp)
D = diagflat(diag)
tA = dot(transpose(A),D)
x = array([1,0,0,0,0,0,0])
pprint(dot(tA,dot(tA,x)))
l, V = eig(tA)
v0 = V[:,0]
pprint(v0)

array([0.35 , 0.167, 0.117, 0.05 , 0.267, 0.05 , 0.   ])
array([0.699+0.j, 0.383+0.j, 0.324+0.j, 0.243+0.j, 0.412+0.j, 0.103+0.j,
       0.14 +0.j])


In [9]:
import numpy as np
from pprint import pprint

np.set_printoptions(formatter={'float': '{: 0.3f}'.format}) 
#pprint(A)
pprint(D)
#pprint(transpose(A))
pprint(tA)
x = array([1,0,0,0,0,0,0])
#pprint(x)
#pprint(dot(tA,dot(tA,dot(tA,x))))
l, V = eig(tA)
v0 = V[:,0]
#pprint(v0)

array([[ 0.200,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000],
       [ 0.000,  1.000,  0.000,  0.000,  0.000,  0.000,  0.000],
       [ 0.000,  0.000,  0.500,  0.000,  0.000,  0.000,  0.000],
       [ 0.000,  0.000,  0.000,  0.333,  0.000,  0.000,  0.000],
       [ 0.000,  0.000,  0.000,  0.000,  0.250,  0.000,  0.000],
       [ 0.000,  0.000,  0.000,  0.000,  0.000,  0.500,  0.000],
       [ 0.000,  0.000,  0.000,  0.000,  0.000,  0.000,  1.000]])
array([[ 0.000,  1.000,  0.500,  0.000,  0.250,  0.500,  0.000],
       [ 0.200,  0.000,  0.500,  0.333,  0.000,  0.000,  0.000],
       [ 0.200,  0.000,  0.000,  0.333,  0.250,  0.000,  0.000],
       [ 0.200,  0.000,  0.000,  0.000,  0.250,  0.000,  0.000],
       [ 0.200,  0.000,  0.000,  0.333,  0.000,  0.500,  1.000],
       [ 0.000,  0.000,  0.000,  0.000,  0.250,  0.000,  0.000],
       [ 0.200,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000]])


In [13]:
#問題2_2
#反復法でのページランク
import numpy as np
from pprint import pprint

np.set_printoptions(formatter={'float': '{: 0.3f}'.format}) 

x = array([1,0,1,1,0,0,0]) ##？？？

for i in range(1,100):
    bef = x
    x = dot(tA,x)
    if sum(abs(bef-x))<0.001:
        break
pprint(x)

array([ 0.911,  0.498,  0.422,  0.316,  0.537,  0.134,  0.182])
